<?php 

// Titles
$labels["plugin_name"]          = "ddnotes";
$labels["browser_title"]        = "Les teves notes";
$labels["title"]                = "Notes";
$labels["notes_list"]           = "Llistat de notes";
$labels["title_toolbar"]        = "Accions sobre la nota";

// Menu
$labels["taskbar_button"]       = "Notes";
$labels["new_note"]             = "Nova";
$labels["edit_note"]            = "Editar";
$labels["send_note"]            = "Enviar";
$labels["delete_note"]          = "Eliminar";
$labels["upload"]               = "Pujar";
$labels["search"]               = "Cercar...";

// Create
$labels["note_title_label"]     = "Títol de la nota";
$labels["note_content_label"]   = "Contingut de la nota";
$labels["note_file_label"]      = "Adjunta un fitxer";
$labels["note_id_label"]        = "ID de la nota";
$labels["note_type_label"]      = "Tipus de la nota";
$labels["create_confirmation"]  = 'Nota creada';
$labels["update_confirmation"]  = "Nota guardada";
$labels["delete_popup"]         = "Estàs segur que desitges eliminar la nota?";
$labels["delete_confirmation"]  = "La nota ha estat eliminada";

// Create - EasyMDE editor icons
$labels["undo"]                 = "Desfer";
$labels["redo"]                 = "Refer";
$labels["bold"]                 = "Negreta";
$labels["italic"]               = "Cursiva";
$labels["strikethrough"]        = "Ratllat";
$labels["heading"]              = "Encapçalat";
$labels["code"]                 = "Codi";
$labels["quote"]                = "Cita";
$labels["generic_list"]         = "Llesta genèrica";
$labels["numberedlist"]         = "Llista numèrica";
$labels["link"]                 = "Enllaç";
$labels["image"]                = "Enllaç d'imatge";
$labels["upload_image"]         = "Puja una imatge";
$labels["table"]                = "Taula";
$labels["horizontal_rule"]      = "Línia horitzontal";
$labels["preview"]              = "Vista prèvia";
$labels["sidebyside"]           = "Costat a costat";
$labels["fullscreen"]           = "Pantalla completa";
$labels["markdown_guide"]       = "Guia de Markdown";

// Show 
$labels["ts_created_label"]     = "Creada";
$labels["ts_updated_label"]     = "Actualitzada";
$labels["type_label"]           = "Tipus";
$labels["format_label"]         = "Format";
$labels["size_label"]           = "Pes";

// Form buttons
$labels["cancel"]               = "Cancel·lar";
$labels["save"]                 = "Guardar";
$labels["update"]               = "Actualitzar";
$labels["download"]             = "Descarregar";

// Errors 
$labels["empty_title"]          = "Haureu d'indicar algun títol";
$labels["no_title"]             = "Sense títol";
$labels["no_note"]              = "La nota que s'intenta carregar no existeix";
$labels["invalid_type"]         = "Format incorrecte";
$labels["no_config"]            = "No ha estat possible carregar la configuració del plugin";
$labels["note_size_error"]      = "El pes total de la nota és massa elevat";
$labels["file_size_error"]      = "El pes de l'arxiu és massa elevat";

// Formats
$labels["markdown"]             = "Markdown";
$labels["html"]                 = "HTML";
$labels["text"]                 = "Texte";
$labels["plain"]                = "Normal";
$labels["image"]                = "Imatge";
$labels["jpeg"]                 = "JPEG";
$labels["jpg"]                  = "JPG";
$labels["png"]                  = "PNG";
$labels["document"]             = "Document";
$labels["application"]          = "Document";
$labels["pdf"]                  = "PDF";
$labels["unknown"]              = "Desconegut";

// Compose subject
$labels["compose_subject"]      = "Nota adjunta: ";

?>