<?php

// Titles
$labels["plugin_name"]          = "ddnotes";
$labels["browser_title"]        = "Deine Noten";
$labels["title"]                = "Anmerkungen";
$labels["notes_list"]           = "Notizenliste";
$labels["title_toolbar"]        = "Aktionen notieren";

// Menu
$labels["taskbar_button"]       = "Anmerkungen";
$labels["new_note"]             = "Neu";
$labels["edit_note"]            = "Bearbeiten";
$labels["send_note"]            = "Senden";
$labels["delete_note"]          = "Löschen";
$labels["upload"]               = "Hochladen";
$labels["search"]               = "Suche...";

// Create
$labels["note_title_label"]     = "Titel notieren";
$labels["note_content_label"]   = "Inhalt beachten";
$labels["note_file_label"]      = "Eine Datei anhängen";
$labels["note_id_label"]        = "Hinweis ID";
$labels["note_type_label"]      = "Notentyp";
$labels["create_confirmation"]  = "Notiz erstellt";
$labels["update_confirmation"]  = "Notiz gespeichert";
$labels["delete_popup"]         = "Sind Sie sicher, dass Sie die Notiz löschen möchten?";
$labels["delete_confirmation"]  = "Notiz wurde gelöscht";

// Create - EasyMDE editor icons
$labels["undo"]                 = "Rückgängig machen";
$labels["redo"]                 = "Wiederherstellen";
$labels["bold"]                 = "Fett gedruckt";
$labels["italic"]               = "Kursiv";
$labels["strikethrough"]        = "Durchgestrichen";
$labels["heading"]              = "Überschrift";
$labels["code"]                 = "Code";
$labels["quote"]                = "Zitat";
$labels["generic_list"]         = "Generische Liste";
$labels["numbered_list"]        = "Numerische Liste";
$labels["link"]                 = "Verknüpfung";
$labels["image"]                = "Bildlink";
$labels["upload_image"]         = "Bild hochladen";
$labels["table"]                = "Tabelle";
$labels["horizontal_rule"]      = "Horizontale Regel";
$labels["preview"]              = "Vorschau";
$labels["sidebyside"]           = "Seite an Seite";
$labels["fullscreen"]           = "Vollbild";
$labels["markdown_guide"]       = "Markdown Guide";

// Show
$labels["ts_created_label"]     = "Erstellt";
$labels["ts_updated_label"]     = "Aktualisiert";
$labels["type_label"]           = "Art";
$labels["format_label"]         = "Format";
$labels["size_label"]           = "Größe";

// Form buttons
$labels["cancel"]               = "Stornieren";
$labels["save"]                 = "Speichern";
$labels["update"]               = "Aktualisieren";
$labels["download"]             = "Herunterladen";

// Errors
$labels["empty_title"]          = "Sie müssen einen Titel angeben";
$labels["no_title"]             = "Kein Titel";
$labels["no_note"]              = "Die Notiz, die Sie laden möchten, existiert nicht.";
$labels["invalid_type"]         = "Falsches Format";
$labels["no_config"]            = "Plugin-Konfiguration konnte nicht geladen werden";
$labels["note_size_error"]      = "Gewicht zu hoch notieren";
$labels["file_size_error"]      = "Dateigewicht zu hoch";

// Formats
$labels["markdown"]             = "Markdown";
$labels["html"]                 = "HTML";
$labels["text"]                 = "Text";
$labels["plain"]                = "Normal";
$labels["image"]                = "Bild";
$labels["jpeg"]                 = "JPEG";
$labels["jpg"]                  = "JPG";
$labels["png"]                  = "PNG";
$labels["document"]             = "Dokument";
$labels["application"]          = "Dokument";
$labels["pdf"]                  = "PDF";
$labels["unknown"]              = "Unbekannt";

// Compose subject
$labels["compose_subject"]      = "Notiz hinzufügen: ";

?>