<?php

// Titles
$labels["plugin_name"]          = "ddnotes";
$labels["browser_title"]        = "Your notes";
$labels["title"]                = "Notes";
$labels["notes_list"]           = "Notes list";
$labels["title_toolbar"]        = "Note actions";

// Menu
$labels["taskbar_button"]       = "Notes";
$labels["new_note"]             = "New";
$labels["edit_note"]            = "Edit";
$labels["delete_note"]          = "Delete";
$labels["upload"]               = "Upload";
$labels["search"]               = "Search...";

// Create
$labels["note_title_label"]     = "Note title";
$labels["note_content_label"]   = "Note content";
$labels["note_file_label"]      = "Attach a file";
$labels["note_id_label"]        = "Note ID";
$labels["note_type_label"]      = "Note Type";
$labels["create_confirmation"]  = "Note created";
$labels["update_confirmation"]  = "Note saved";
$labels["delete_popup"]         = "Are you sure you want to delete the note?";
$labels["delete_confirmation"]  = "Note has been deleted";

// Create - EasyMDE editor icons
$labels["undo"]                 = "Undo";
$labels["redo"]                 = "Redo";
$labels["bold"]                 = "Bold";
$labels["italic"]               = "Italic";
$labels["strikethrough"]        = "Strikethrough";
$labels["heading"]              = "Heading";
$labels["code"]                 = "Code";
$labels["quote"]                = "Quote";
$labels["generic_list"]         = "Generic List";
$labels["numbered_list"]        = "Numeric list";
$labels["link"]                 = "Link";
$labels["image"]                = "Image link";
$labels["upload_image"]         = "Upload image";
$labels["table"]                = "Table";
$labels["horizontal_rule"]      = "Horizontal rule";
$labels["preview"]              = "Preview";
$labels["sidebyside"]           = "Side by side";
$labels["fullscreen"]           = "Fullscreen";
$labels["markdown_guide"]       = "Markdown Guide";

// Show
$labels["ts_created_label"]     = "Created";
$labels["ts_updated_label"]     = "Updated";
$labels["type_label"]           = "Type";
$labels["format_label"]         = "Format";
$labels["size_label"]           = "Size";

// Form buttons
$labels["cancel"]               = "Cancel";
$labels["save"]                 = "Save";
$labels["update"]               = "Update";
$labels["download"]             = "Download";

// Errors
$labels["empty_title"]          = "You must indicate some title";
$labels["no_title"]             = "No title";
$labels["no_note"]              = "The note you are trying to load does not exist";
$labels["invalid_type"]         = "Incorrect format";
$labels["no_config"]            = "Failed to load plugin configuration";
$labels["note_size_error"]      = "Total weight of note too high";
$labels["file_size_error"]      = "File weight too high";

// Formats
$labels["markdown"]             = "Markdown";
$labels["html"]                 = "HTML";
$labels["text"]                 = "Text";
$labels["plain"]                = "Normal";
$labels["image"]                = "Image";
$labels["jpeg"]                 = "JPEG";
$labels["jpg"]                  = "JPG";
$labels["png"]                  = "PNG";
$labels["document"]             = "Document";
$labels["application"]          = "Document";
$labels["pdf"]                  = "PDF";
$labels["unknown"]              = "Unkown";

?>