<?php

// Titles
$labels["plugin_name"]          = "ddnotes";
$labels["browser_title"]        = "Tus notas";
$labels["title"]                = "Notas";
$labels["notes_list"]           = "Listado de notas";
$labels["title_toolbar"]        = "Acciones sobre la nota";

// Menu
$labels["taskbar_button"]       = "Notas";
$labels["new_note"]             = "Nueva";
$labels["edit_note"]            = "Editar";
$labels["send_note"]            = "Enviar";
$labels["delete_note"]          = "Eliminar";
$labels["upload"]               = "Subir";
$labels["search"]               = "Buscar...";

// Create
$labels["note_title_label"]     = "Título de la nota";
$labels["note_content_label"]   = "Contenido de la nota";
$labels["note_file_label"]      = "Adjunta un archivo";
$labels["note_id_label"]        = "ID de la nota";
$labels["note_type_label"]      = "Tipo de la nota";
$labels["create_confirmation"]  = "Nota creada";
$labels["update_confirmation"]  = "Nota guardada";
$labels["delete_popup"]         = "¿Estas seguro que deseas eliminar la nota?";
$labels["delete_confirmation"]  = "La nota ha sido borrada";

// Create - EasyMDE editor icons
$labels["undo"]                 = "Deshacer";
$labels["redo"]                 = "Rehacer";
$labels["bold"]                 = "Negrita";
$labels["italic"]               = "Cursiva";
$labels["strikethrough"]        = "Tachado";
$labels["heading"]              = "Encabezado";
$labels["code"]                 = "Código";
$labels["quote"]                = "Cita";
$labels["generic_list"]         = "Lista genérica";
$labels["numbered_list"]        = "Lista numérica";
$labels["link"]                 = "Enlace";
$labels["image"]                = "Enlace a imagen";
$labels["upload_image"]         = "Sube una imagen";
$labels["table"]                = "Tabla";
$labels["horizontal_rule"]      = "Línea horizontal";
$labels["preview"]              = "Vista previa";
$labels["sidebyside"]           = "Lado a lado";
$labels["fullscreen"]           = "Pantalla completa";
$labels["markdown_guide"]       = "Guía de Markdown";

// Show
$labels["ts_created_label"]     = "Creada";
$labels["ts_updated_label"]     = "Actualitzada";
$labels["type_label"]           = "Tipo";
$labels["format_label"]         = "Formato";
$labels["size_label"]           = "Peso";

// Form buttons
$labels["cancel"]               = "Cancelar";
$labels["save"]                 = "Guardar";
$labels["update"]               = "Actualizar";
$labels["download"]             = "Descargar";

// Errors
$labels["empty_title"]          = "Debes indicar un título";
$labels["no_title"]             = "No title";
$labels["no_note"]              = "La nota que se intenta cargar no existe";
$labels["invalid_type"]         = "Formato incorrecto";
$labels["no_config"]            = "No ha sido posible cargar la configuración del plugin";
$labels["note_size_error"]      = "El peso total de la nota es demasiado elevado";
$labels["file_size_error"]      = "El peso del archivo es demasiado elevado";

// Formats
$labels["markdown"]             = "Markdown";
$labels["html"]                 = "HTML";
$labels["text"]                 = "Texto";
$labels["plain"]                = "Normal";
$labels["image"]                = "Imagen";
$labels["jpeg"]                 = "JPEG";
$labels["jpg"]                  = "JPG";
$labels["png"]                  = "PNG";
$labels["document"]             = "Documento";
$labels["application"]          = "Documento";
$labels["pdf"]                  = "PDF";
$labels["unknown"]              = "Desconocido";

// Compose subject
$labels["compose_subject"]      = "Nota adjunta: ";

?>