<?php

// Titles
$labels["plugin_name"]          = "ddnotes";
$labels["browser_title"]        = "Vos notes";
$labels["title"]                = "Notes";
$labels["notes_list"]           = "Liste des notes";
$labels["title_toolbar"]        = "Notez les actions";

// Menu
$labels["taskbar_button"]       = "Notes";
$labels["new_note"]             = "Nouveau";
$labels["edit_note"]            = "Modifier";
$labels["send_note"]            = "Envoyer";
$labels["delete_note"]          = "Supprimer";
$labels["upload"]               = "Télécharger";
$labels["search"]               = "Rechercher ...";

// Create
$labels["note_title_label"]     = "Titre de la note";
$labels["note_content_label"]   = "Contenu de la note";
$labels["note_file_label"]      = "Joindre un fichier";
$labels["note_id_label"]        = "ID de la note";
$labels["note_type_label"]      = "Type de note";
$labels["create_confirmation"]  = "Note créée";
$labels["update_confirmation"]  = "Note enregistrée";
$labels["delete_popup"]         = "Voulez-vous vraiment supprimer la note?";
$labels["delete_confirmation"]  = "La note a été supprimée";

// Create - EasyMDE editor icons
$labels["undo"]                 = "Annuler";
$labels["redo"]                 = "Refaire";
$labels["bold"]                 = "Gras";
$labels["italic"]               = "Italique";
$labels["strikethrough"]        = "Barré";
$labels["heading"]              = "Titre";
$labels["code"]                 = "Code";
$labels["quote"]                = "Citation";
$labels["generic_list"]         = "Liste générique";
$labels["numbered_list"]        = "Liste numérique";
$labels["link"]                 = "Lien";
$labels["image"]                = "Lien d'image";
$labels["upload_image"]         = "Télécharger une image";
$labels["table"]                = "Table";
$labels["horizontal_rule"]      = "Règle horizontale";
$labels["preview"]              = "Aperçu";
$labels["sidebyside"]           = "Côte à côte";
$labels["fullscreen"]           = "Plein écran";
$labels["markdown_guide"]       = "Guide de démarque";

// Show
$labels["ts_created_label"]     = "Créé";
$labels["ts_updated_label"]     = "Mis à jour";
$labels["type_label"]           = "Type";
$labels["format_label"]         = "Format";
$labels["size_label"]           = "Taille";

// Form buttons
$labels["cancel"]               = "Annuler";
$labels["save"]                 = "Enregistrer";
$labels["update"]               = "Mettre à jour";
$labels["download"]             = "Télécharger";

// Errors
$labels["empty_title"]          = "Vous devez indiquer un titre";
$labels["no_title"]             = "Aucun titre";
$labels["no_note"]              = "La note que vous essayez de charger n'existe pas";
$labels["invalid_type"]         = "Format incorrect";
$labels["no_config"]            = "Échec du chargement de la configuration du plugin";
$labels["note_size_error"]      = "Note poids trop élevé";
$labels["file_size_error"]      = "Poids du fichier trop élevé";

// Formats
$labels["markdown"]             = "Markdown";
$labels["html"]                 = "HTML";
$labels["text"]                 = "Texte";
$labels["plain"]                = "Normal";
$labels["image"]                = "Image";
$labels["jpeg"]                 = "JPEG";
$labels["jpg"]                  = "JPG";
$labels["png"]                  = "PNG";
$labels["document"]             = "Document";
$labels["application"]          = "Document";
$labels["pdf"]                  = "PDF";
$labels["unknown"]              = "Inconnu";

// Compose subject
$labels["compose_subject"]      = "Note jointe: ";

?>